### PR TITLE
Adding option to trigger crossfade before we get to object

### PR DESCRIPTION
**Pull request by erikreyna**
See lines 254 and 353. Also updated the index.html file to show the new option.

### CODE REVIEW

**Comment by mikefowler** [comment]
This diff is super noisy because all of the indentation was changed. Could you resubmit without all the whitespace and indentation diffs?

**Comment by erikreyna** [comment]
No problem. Some of that was the linter throwing errors and others I
believe was the editor converting tabs to spaces.

Will get to it this ASAP. My apologies.

**Comment by erikreyna** [comment]
@mikefowler latest commit (98589199a192ca14a15fc3f301011178141581da) reflects the small additions I made without the whitespace modifications.

**Comment by mikefowler** [comment]
Looks good to me, @erikreyna. Thanks!

**Comment by erikreyna** [comment]
Word! It was the least I could do! Otherwise I would have spent time rolling my own. Cheers :beers:

**Comment by erikreyna** [comment]
Double :beers: for this being my first PR ever too.

**Comment by mikefowler** [comment]
fuckyea

**Pull request merged**
